version: '3'

services:
  workspace:
    build: .
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "8888:8888"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"