### Check Elasticsearch cluster health
GET http://elasticsearch:9200/_cluster/health

### Check cluster info
GET http://elasticsearch:9200

### Create an index
PUT http://elasticsearch:9200/my-index
Content-Type: application/json

{
    "settings": {
        "number_of_shards": 1,
        "number_of_replicas": 0
    },
    "mappings": {
        "properties": {
            "title": { "type": "text" },
            "description": { "type": "text" },
            "price": { "type": "float" },
            "created_at": { "type": "date" }
        }
    }
}

### Index a document
POST http://elasticsearch:9200/my-index/_doc
Content-Type: application/json

{
    "title": "Sample Product",
    "description": "This is a sample product for testing Elasticsearch",
    "price": 29.99,
    "created_at": "2024-01-15"
}

### Search all documents
GET http://elasticsearch:9200/my-index/_search
Content-Type: application/json

{
    "query": {
        "match_all": {}
    }
}

### Search with query
GET http://elasticsearch:9200/my-index/_search
Content-Type: application/json

{
    "query": {
        "match": {
            "description": "sample"
        }
    }
}

### List all indices
GET http://elasticsearch:9200/_cat/indices?v

### Delete the index
DELETE http://elasticsearch:9200/my-index
